-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS inspectiondone CASCADE;
DROP TABLE IF EXISTS inspectionformfield CASCADE;
DROP TABLE IF EXISTS inspectionformheader CASCADE;
DROP TABLE IF EXISTS linkreminderapiary CASCADE;
DROP TABLE IF EXISTS reminder CASCADE;
DROP TABLE IF EXISTS apiary CASCADE;
DROP TABLE IF EXISTS queen CASCADE;
DROP TABLE IF EXISTS hive CASCADE;
DROP TABLE IF EXISTS beekeeper CASCADE;
