-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS QueenInspection CASCADE;
DROP TABLE IF EXISTS ApiaryInspection CASCADE;
DROP TABLE IF EXISTS InspectionField CASCADE;
DROP TABLE IF EXISTS InspectionHeader CASCADE;
DROP TABLE IF EXISTS Reminder CASCADE;
DROP TABLE IF EXISTS Apiary CASCADE;
DROP TABLE IF EXISTS Queen CASCADE;
DROP TABLE IF EXISTS Hive CASCADE;
DROP TABLE IF EXISTS Beekeeper CASCADE;
