-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS queeninspection CASCADE;
DROP TABLE IF EXISTS apiaryinspection CASCADE;
DROP TABLE IF EXISTS inspectionfield CASCADE;
DROP TABLE IF EXISTS inspectionheader CASCADE;
DROP TABLE IF EXISTS reminder CASCADE;
DROP TABLE IF EXISTS apiary CASCADE;
DROP TABLE IF EXISTS queen CASCADE;
DROP TABLE IF EXISTS hive CASCADE;
DROP TABLE IF EXISTS beekeeper CASCADE;
